### ISSUE TITLE
Does python-numpy-mkl really depend on 'intel-compiler-base', since the PKGBUILD uses gcc?

### ISSUE THREAD

**Issue by ArniDagur** [mratsim/Arch-Machine-Learning#6]
https://github.com/mratsim/Arch-Data-Science/blob/master/python-numpy-mkl/PKGBUILD#L15-L19

**Comment by mratsim** [comment]
Yes, to setup MKL environment variables via `/opt/intel/mkl/bin/mklvars.sh`

Actually with those variables the compiler will switch to ICC. I didn't investigate more in which cases though.
